/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v8.0
processor: MK66FN2M0xxx18
package_id: MK66FN2M0VMD18
mcu_data: ksdk2_0
processor_version: 8.0.1
board: FRDM-K66F
pin_labels:
- {pin_num: A6, pin_signal: PTC16/CAN1_RX/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b/SDRAM_DQM2, label: 'J1[6]/ENET0_1588_TMR0', identifier: ENET0_1588_TMR0;LCD_DB5}
- {pin_num: A7, pin_signal: PTC12/UART4_RTS_b/FTM_CLKIN0/FB_AD27/SDRAM_D27/FTM3_FLT0/TPM_CLKIN0, label: 'J1[10]/FB_AD27', identifier: FB_AD27;LCD_E}
- {pin_num: A8, pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7/SDRAM_A15, label: 'J1[8]/FTM3_CH4/ADC1_SE4b', identifier: FTM3_CH4;LCD_DB4}
- {pin_num: D8, pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/SDRAM_A18/CMP0_OUT/FTM0_CH2, label: 'J1[12]/I2S0_RXD0/FB_AD10/FTM0_CH2', identifier: FB_AD10;LCD_RW}
- {pin_num: A9, pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/SDRAM_A19/CMP1_OUT, label: 'J1[4]/UART1_TX/FTM0_CH3/FB_AD11', identifier: UART1_TX;LCD_DB6}
- {pin_num: A11, pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK, label: 'J1[2]/UART1_RX/FTM0_CH2/CLKOUT', identifier: UART1_RX;LCD_DB7}
- {pin_num: A12, pin_signal: ADC0_SE4b/CMP1_IN0/TSI0_CH15/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/SDRAM_A20/I2S0_TX_FS, label: 'J1[14]/FTM0_CH1/CMP1_IN0/FB_AD12',
  identifier: FTM0_CH1;LCD_RS;LCD_RW}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: '', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: E10, peripheral: UART0, signal: RX, pin_signal: TSI0_CH9/PTB16/SPI1_SOUT/UART0_RX/FTM_CLKIN0/FB_AD17/SDRAM_D17/EWM_IN/TPM_CLKIN0}
  - {pin_num: E9, peripheral: UART0, signal: TX, pin_signal: TSI0_CH10/PTB17/SPI1_SIN/UART0_TX/FTM_CLKIN1/FB_AD16/SDRAM_D16/EWM_OUT_b/TPM_CLKIN1}
  - {pin_num: A12, peripheral: GPIOC, signal: 'GPIO, 2', pin_signal: ADC0_SE4b/CMP1_IN0/TSI0_CH15/PTC2/SPI0_PCS2/UART1_CTS_b/FTM0_CH1/FB_AD12/SDRAM_A20/I2S0_TX_FS,
    identifier: LCD_RS, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: D8, peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/SDRAM_A18/CMP0_OUT/FTM0_CH2, identifier: LCD_RW,
    direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: A7, peripheral: GPIOC, signal: 'GPIO, 12', pin_signal: PTC12/UART4_RTS_b/FTM_CLKIN0/FB_AD27/SDRAM_D27/FTM3_FLT0/TPM_CLKIN0, identifier: LCD_E, direction: OUTPUT,
    gpio_init_state: 'false'}
  - {pin_num: A8, peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: ADC1_SE4b/CMP0_IN2/PTC8/FTM3_CH4/I2S0_MCLK/FB_AD7/SDRAM_A15, identifier: LCD_DB4, direction: OUTPUT,
    gpio_init_state: 'false'}
  - {pin_num: A6, peripheral: GPIOC, signal: 'GPIO, 16', pin_signal: PTC16/CAN1_RX/UART3_RX/ENET0_1588_TMR0/FB_CS5_b/FB_TSIZ1/FB_BE23_16_BLS15_8_b/SDRAM_DQM2, identifier: LCD_DB5,
    direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: A9, peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/FTM0_CH3/FB_AD11/SDRAM_A19/CMP1_OUT, identifier: LCD_DB6, direction: OUTPUT,
    gpio_init_state: 'false'}
  - {pin_num: A11, peripheral: GPIOC, signal: 'GPIO, 3', pin_signal: CMP1_IN1/PTC3/LLWU_P7/SPI0_PCS1/UART1_RX/FTM0_CH2/CLKOUT/I2S0_TX_BCLK, identifier: LCD_DB7, direction: OUTPUT,
    gpio_init_state: 'false'}
  - {pin_num: L3, peripheral: DAC0, signal: OUT, pin_signal: DAC0_OUT/CMP1_IN3/ADC0_SE23}
  - {pin_num: H5, peripheral: DAC0, signal: REF_2, pin_signal: VDDA}
  - {pin_num: F11, peripheral: ADC1, signal: 'SE, 13', pin_signal: ADC1_SE13/PTB7/FB_AD22/SDRAM_D22}
  - {pin_num: J3, peripheral: ADC0, signal: 'SE, 16', pin_signal: ADC0_SE16/CMP1_IN2/ADC0_SE21}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);

    gpio_pin_config_t LCD_RS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC2 (pin A12)  */
    GPIO_PinInit(LCD_RS_GPIO, LCD_RS_PIN, &LCD_RS_config);

    gpio_pin_config_t LCD_DB7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC3 (pin A11)  */
    GPIO_PinInit(LCD_DB7_GPIO, LCD_DB7_PIN, &LCD_DB7_config);

    gpio_pin_config_t LCD_DB6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC4 (pin A9)  */
    GPIO_PinInit(LCD_DB6_GPIO, LCD_DB6_PIN, &LCD_DB6_config);

    gpio_pin_config_t LCD_RW_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC5 (pin D8)  */
    GPIO_PinInit(LCD_RW_GPIO, LCD_RW_PIN, &LCD_RW_config);

    gpio_pin_config_t LCD_DB4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC8 (pin A8)  */
    GPIO_PinInit(LCD_DB4_GPIO, LCD_DB4_PIN, &LCD_DB4_config);

    gpio_pin_config_t LCD_E_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC12 (pin A7)  */
    GPIO_PinInit(LCD_E_GPIO, LCD_E_PIN, &LCD_E_config);

    gpio_pin_config_t LCD_DB5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC16 (pin A6)  */
    GPIO_PinInit(LCD_DB5_GPIO, LCD_DB5_PIN, &LCD_DB5_config);

    /* PORTB16 (pin E10) is configured as UART0_RX */
    PORT_SetPinMux(DEBUG_UART_RX_PORT, DEBUG_UART_RX_PIN, kPORT_MuxAlt3);

    /* PORTB17 (pin E9) is configured as UART0_TX */
    PORT_SetPinMux(DEBUG_UART_TX_PORT, DEBUG_UART_TX_PIN, kPORT_MuxAlt3);

    /* PORTB7 (pin F11) is configured as ADC1_SE13 */
    PORT_SetPinMux(ADC1_SE13_PORT, ADC1_SE13_PIN, kPORT_PinDisabledOrAnalog);

    /* PORTC12 (pin A7) is configured as PTC12 */
    PORT_SetPinMux(LCD_E_PORT, LCD_E_PIN, kPORT_MuxAsGpio);

    /* PORTC16 (pin A6) is configured as PTC16 */
    PORT_SetPinMux(LCD_DB5_PORT, LCD_DB5_PIN, kPORT_MuxAsGpio);

    /* PORTC2 (pin A12) is configured as PTC2 */
    PORT_SetPinMux(LCD_RS_PORT, LCD_RS_PIN, kPORT_MuxAsGpio);

    /* PORTC3 (pin A11) is configured as PTC3 */
    PORT_SetPinMux(LCD_DB7_PORT, LCD_DB7_PIN, kPORT_MuxAsGpio);

    /* PORTC4 (pin A9) is configured as PTC4 */
    PORT_SetPinMux(LCD_DB6_PORT, LCD_DB6_PIN, kPORT_MuxAsGpio);

    /* PORTC5 (pin D8) is configured as PTC5 */
    PORT_SetPinMux(LCD_RW_PORT, LCD_RW_PIN, kPORT_MuxAsGpio);

    /* PORTC8 (pin A8) is configured as PTC8 */
    PORT_SetPinMux(LCD_DB4_PORT, LCD_DB4_PIN, kPORT_MuxAsGpio);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART0TXSRC_MASK)))

                  /* UART 0 transmit data source select: UART0_TX pin. */
                  | SIM_SOPT5_UART0TXSRC(SOPT5_UART0TXSRC_UART_TX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
