/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART 0 transmit data source select: UART0_TX pin */

/*! @name PORTB16 (coord E10), U7[4]/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define DEBUG_UART_RX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define DEBUG_UART_RX_PIN 16U                   /*!<@brief PORT pin number */
#define DEBUG_UART_RX_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTB17 (coord E9), U10[1]/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define DEBUG_UART_TX_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define DEBUG_UART_TX_PIN 17U                   /*!<@brief PORT pin number */
#define DEBUG_UART_TX_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORTC2 (coord A12), J1[14]/FTM0_CH1/CMP1_IN0/FB_AD12
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_RS_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define LCD_RS_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_RS_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define LCD_RS_PIN 2U                   /*!<@brief PORT pin number */
#define LCD_RS_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                        /* @} */

/*! @name PORTC5 (coord D8), J1[12]/I2S0_RXD0/FB_AD10/FTM0_CH2
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_RW_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define LCD_RW_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_RW_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define LCD_RW_PIN 5U                   /*!<@brief PORT pin number */
#define LCD_RW_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                        /* @} */

/*! @name PORTC12 (coord A7), J1[10]/FB_AD27
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_E_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define LCD_E_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_E_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define LCD_E_PIN 12U                   /*!<@brief PORT pin number */
#define LCD_E_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                        /* @} */

/*! @name PORTC8 (coord A8), J1[8]/FTM3_CH4/ADC1_SE4b
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB4_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define LCD_DB4_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB4_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define LCD_DB4_PIN 8U                   /*!<@brief PORT pin number */
#define LCD_DB4_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name PORTC16 (coord A6), J1[6]/ENET0_1588_TMR0
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB5_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define LCD_DB5_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB5_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define LCD_DB5_PIN 16U                   /*!<@brief PORT pin number */
#define LCD_DB5_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name PORTC4 (coord A9), J1[4]/UART1_TX/FTM0_CH3/FB_AD11
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB6_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define LCD_DB6_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB6_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define LCD_DB6_PIN 4U                   /*!<@brief PORT pin number */
#define LCD_DB6_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name PORTC3 (coord A11), J1[2]/UART1_RX/FTM0_CH2/CLKOUT
  @{ */

/* Symbols to be used with GPIO driver */
#define LCD_DB7_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define LCD_DB7_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LCD_DB7_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define LCD_DB7_PIN 3U                   /*!<@brief PORT pin number */
#define LCD_DB7_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                         /* @} */

/*! @name DAC0_OUT (coord L3), J4[11]/DAC_OUT
  @{ */
/* @} */

/*! @name PORTB7 (coord F11), J4[2]/ADC1_SE13
  @{ */

/* Symbols to be used with PORT driver */
#define ADC1_SE13_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define ADC1_SE13_PIN 7U                   /*!<@brief PORT pin number */
#define ADC1_SE13_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name ADC0_SE16 (coord J3), J4[5]/ADC0
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
