/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_pit.h"
#include "fsl_uart.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for PIT */
/* Definition of peripheral ID. */
#define PIT_1_PERIPHERAL PIT
/* Definition of clock source. */
#define PIT_1_CLOCK_SOURCE kCLOCK_BusClk
/* Definition of clock source frequency. */
#define PIT_1_CLK_FREQ 60000000UL
/* Definition of ticks count for channel 1 - deprecated. */
#define PIT_1_1_TICKS 59999999U
/* Definition of channel number for channel 1. */
#define PIT_1_1 kPIT_Chnl_1
/* PIT_1 interrupt vector ID (number). */
#define PIT_1_1_IRQN PIT1_IRQn
/* PIT_1 interrupt handler identifier. */
#define PIT_1_1_IRQHANDLER PIT1_IRQHandler
/* Definition of peripheral ID */
#define UART_PERIPHERAL UART3
/* Definition of the clock source frequency */
#define UART_CLOCK_SOURCE 60000000UL
/* UART interrupt vector ID (number). */
#define UART_SERIAL_RX_TX_IRQN UART3_RX_TX_IRQn
/* UART interrupt handler identifier. */
#define UART_SERIAL_RX_TX_IRQHANDLER UART3_RX_TX_IRQHandler
/* UART interrupt vector ID (number). */
#define UART_SERIAL_ERROR_IRQN UART3_ERR_IRQn
/* UART interrupt handler identifier. */
#define UART_SERIAL_ERROR_IRQHANDLER UART3_ERR_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const pit_config_t PIT_1_config;
extern const uart_config_t UART_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
