from turtle import Turtle, done
import time
paja = Turtle()
paja.speed(15)
none=10
letterdistance=15


paja.penup()
def S():
    paja.left(90)
    paja.forward(40)
    paja.right(90)
    paja.forward(20)
    paja.pendown()
    paja.left(180)
    paja.forward(20)
    paja.left(90)
    paja.forward(20)
    paja.left(90)
    paja.forward(20)
    paja.right(90)
    paja.forward(20)
    paja.right(90)
    paja.forward(20)
    paja.left(180)
    paja.forward(20)
    paja.penup()
    paja.forward(letterdistance)
    
def E():
    paja.pendown()
    paja.left(90)
    paja.forward(40)
    paja.right(90)
    paja.forward(20)
    paja.right(90)
    paja.forward(20)
    paja.right(90)
    paja.forward(20)
    paja.left(90)
    paja.forward(20)
    paja.left(90)
    paja.forward(20)
    paja.penup()
    paja.forward(letterdistance)
    
def N():
    paja.pendown()
    paja.left(90)
    paja.forward(40)
    paja.right(90)
    for i in range(9):
        paja.forward(2)
        paja.right(90)
        paja.forward(4)
        paja.left(90)
    paja.right(90)
    paja.forward(4)
    paja.left(180)
    paja.forward(40)
    paja.left(180)
    paja.forward(40)
    paja.left(90)
    paja.penup()
    paja.forward(letterdistance)

def D():
    paja.pendown()
    paja.left(90)
    paja.forward(40)
    paja.right(90)
    paja.forward(17)
    paja.right(45)
    paja.forward(5)
    paja.right(45)
    paja.forward(34)
    paja.right(45)
    paja.forward(5)
    paja.right(45)
    paja.forward(17)
    paja.left(180)
    paja.penup()
    paja.forward(20)
    paja.forward(letterdistance)
    
def U():
    paja.left(90)
    paja.forward(8)
    paja.pendown()
    paja.forward(32)
    paja.left(180)
    paja.forward(32)
    paja.left(45)
    paja.forward(10)
    paja.left(45)
    paja.forward(8)
    paja.left(45)
    paja.forward(10)
    paja.left(45)
    paja.forward(32)
    paja.penup()
    paja.left(180)
    paja.forward(40)
    paja.left(90)
    paja.forward(letterdistance)

def nextline():
    paja.right(90)
    paja.forward(55)
    paja.right(90)
    paja.forward(90)
    paja.right(180)
    
S()
E()
N()
D()
nextline()
N()
U()
D()
E()
S()
time.sleep(3)
