---
title: "Cvičení 4: Vícerozměrná pole a ukazatelová aritmetika"
layout: "seminar"
authors:
  - xjaros1
publish: 1
---

V minulém cvičení jsme započali strastiplnou cestu k pochopení ukazatelů a polí.
Nyní budeme v této cestě pokračovat, a to výpravou do vyšších dimenzí.

WARNING: Pozor, ukazatelů se již do konce semestru nezbavíme a navíc budou
hrát téměř vždy klíčovou roli! Doporučujeme proto nezaspat a pokusit se pochopit
tyto koncepty, než bude pozdě.

== Piškvorky

Nejdříve se zaměříme na orientaci ve vícerozměrných polích, tedy jak je deklarovat,
a následně jak je používat.

=== Úkol 1: Hra

Jako první úkol doimplementujeme jednoduchou konzolovou hru piškvorek.
V zdrojovém souboru `tictac.c` máte již rozpracovanou implementaci s běhovým
rozhraním, které umí obsloužit celou hru. Nicméně, pro úspěšné hraní je potřeba
doimplementovat dvě funkce

[source,c]
----
int playTurn(char board[BOARD_SIZE][BOARD_SIZE], short iteration, char playerNames[2][STRING_SIZE]);
int checkWinningMove(char board[BOARD_SIZE][BOARD_SIZE]);
----

kde

* `playTurn` realizuje zpracovaní vstupu od jednoho hráče,
** na začátku kola vypíše jméno aktuálního hráče a načte dvě čísla reprezentující
umístění znaku daného hráče,
** určení znaku hráče provede na základě proměnné `iteration`, která reprezentuje
hrané kolo,
** první hráč umísťuje křížky a první iterace má index `0`, tedy iterace dělitelná dvěma je hrou
křížků,
** pozice jména v poli jmen odpovídá iteraci stejným způsobem (nulté je křížek, první je kolečko),
** pokud se nepodaří zpracovat vstup, funkce vrátí hodnotu `GAMEPLAY_ERROR`,
** pokud se zpracování podaří, vrací `GAMEPLAY_OK`,

//-

* `checkWinningMove` kontroluje, zda některý z hráčů hru vyhrál.
** Vítězem je hráč, kterému se podaří jeho znak umístit do řady o délce 5 buď
*** v řádku,
*** ve sloupci,
*** po diagonále.
** Pokud zatím nebyla nalezena žádná vítězná posloupnost, funkce vrátí hodnotu `NOBODY_WON`.
** Pokud vyhrály křížky, respektive kolečka, funkce vrátí `XS_WON` respektive `OS_WON`.
** Pokud na herní ploše neexistuje žádné volné místo a zároveň nebyl nalezen vítězný tah,
funkce vrátí hodnotu `DRAW`.

NOTE: Při implementaci algoritmu pro `checkWinningMove` si rozmyslete, jakým způsobem
procházíte pole. Není potřeba se vydávat všemi směry, pokud víte, že jdete z vrchu dolů a zleva
doprava (a stejná analogie bude platit i pro diagonály).


== Matice

Po zbytek tohoto cvičení budeme pracovat s maticemi, přepněte si proto cíl
v na `matrixCalc` a upravujte soubor `matrix.c`.


=== Úkol 2: Základní vlastnosti vícerozměrných polí

* Deklarujte v souboru `matrix.c` proměnnou `matrix` typu dvojrozměrné pole (necháme čistě
na vás, zda se bude jednat o čtvercové pole či nikoliv).
* Vypište na standardní výstup následující ukazatele:
** `matrix` ve formátu `matrix is pointing to ADDRESS with size of SIZE`,
** `matrix[0]` ve formátu `matrix[0] is pointing to ADDRESS with size of SIZE`,
** `matrix[1]` ve formátu `matrix[1] is pointing to ADDRESS with size of SIZE`,
** `&matrix[1][1]` ve formátu `matrix[1][1] si pointing to ADDRESS with size of SIZE`,
* kde `ADDRESS` je celé číslo indikující adresu.
* Pro výpis ukazatele použijte formátovací značku `%p`.
* Pro výpis velikosti použijte značku `%zu`, jehož hodnota bude určena operátorem `sizeof`.
* Prohlédněte si výpis a zamyslete se nad tím, proč takto vypadá.

[NOTE]
=====
Možná vás výpis zarazil, proto si zde pokusíme trošku vysvětlit, proč se vícerozměrná
pole takto chovají.

Vícerozměrná pole fungují v principu úplně stejně jako jednorozměrná, tedy jedná se o
vyhrazený region v paměti, kde jsou prvky naskládány přímo za sebe, proto se lze na
vícerozměrná pole typu `int array[M][N][K]..[Z]` dívat jako na jednorozměrná pole
`int array[M*N*K*\...*Z]`. Nicméně, aby nám kompilátor zachoval určitou pohodlnost
používání těchto polí, dokáže na základě typu odvodit, kdy přistupujeme k určité
rovině (nebo chcete-li k podprostoru -- například řádek matice, rovina v
prostoru), nebo jsme již operátor `[]` použili tolikrát, že přistupujeme ke
konkrétní hodnotě.
=====

=== Úkol 3: Násobení skalárem

Nyní zkusíme naprogramovat první předání matice do funkce, implementujte funkci

[source,c]
----
void multiplyMatrix(int mrows, int mcols, int matrix[mrows][mcols], int number);
----

která vynásobí matici zadaným skalárem.

Pro testování můžete matici inicializovat náhodnými čísly pomocí funkce `fillMatrix`,
která očekává atributy

* `int minValue` -- minimální hodnota pro generování,
* `int maxValue` -- maximální hodnota pro generování,
* `size_t mrows, size_t mcols` -- rozměry matice,
* `int matrix[mrows][mcols]` -- matice samotná.


=== Úkol 4: Matice jako pole

Nyní se na okamžik vrátíme k minulému cvičení, kde jsme implementovali funkci

[source,c]
----
int findMaxMinInArray(size_t length, int *array, int *max, int *min);
----

Vaším úkolem nyní bude si zkusit tuto funkci použít pro nalezení maxima a minima:

* Nejdříve pro celou matici a vypsat `Max: MAX, Min: MIN`,
* potom pro každý řádek zvlášť a vypsat `Row no. NUM, max: MAXVALUE, min: MINVALUE`,
* využijte toho, že vaše matice je „přetypovatelná“na jednorozměrné pole.

NOTE: Pokud jste minulý týden nestihli implementovat funkci `findMaxMinInArray`, stáhněte si ji
ze zveřejněné implementace pro minulý týden link:../seminar-03/pb071-seminar-03-solution.zip[zde].

=== Úkol 5: Určení pozice maxima a minima

Nyní se ponoříme do základů ukazatelové aritmetiky. Zkusíme upravit funkci `findMaxMinInArray` tak,
aby nám místo hodnoty maxima, respektive minima, nastavila přímo ukazatele do matice.

* Vytvořte funkci `findMaxMinPointers`, která bude kopií funkce `findMaxMinInArray`.
* Upravte argumenty `min` a `max` z typu +++<code>int *</code>+++ na typ +++<code>int **</code>+++ (proč?).
* Ve funkci main přidejte výpis `Found max in matrix VALUE on coordinates [ROW][COL]`
* Ve funkci main přidejte výpis `Found min in matrix VALUE on coordinates [ROW][COL]`

TIP: Pro tento úkol je vhodné využít pohledu na matici, jako na jednorozměrné pole.
Potom totiž můžeme využít aritmetické vlastnosti ukazatele, jako například toho, že
rozdíl dvou ukazatelů nám vrací jejich vzdálenost.

=== Úkol 6: Hledání palindromů mezi řádky

Jako poslední úkol si zkusíme s použitím ukazatelové aritmetiky zjistit, které řádky matice jsou
palindromy. V tomto kontextu budeme palindromem rozumět pole, které je symetrické vzhledem ke
svému středu, tedy pole bude vypadat stejně při čtení zepředu i zezadu. Například:

* `[1, 2, 3, 2, 1]` je palindromem,
* `[3, 3, 3, 3]` je palindromem,
* `[1, 2, 3, 4, 4, 3, 2, 1]` je palindromem,
* `[1, 2, 3, 4, 3, 2]` palindromem není,
* `[1, 2, 3, 4, 5, 6]` taktéž není.

Napište funkci

[source,c]
----
int findPalindromes(size_t mrows, size_t mcols, int matrix[mrows][mcols], short palindromes[mrows]);
----

která pro každý řádek ověří, zda je palindromem a uloží tuto informaci na odpovídající
index do pole `palindromes` jako:

* hodnotu `1`, pokud je palindromem,
* hodnotu `0`, pokud není.

Funkce bude vracet počet nalezených palindromů.

[NOTE]
====

Ačkoliv by tato funkce šla implementovat čistě pomocí indexů, ve spoustě případů (tento nevyjímaje)
je vhodné použit pro pohyb v poli čistý ukazatel, protože tento zápis zvyšuje čitelnost kódu a
usnadňuje jeho porozumění. Proto doporučujeme místo proměnných typu `size_t` pro reprezentaci indexů
a následného použití operátoru `[]`, použít dvě proměnné typu `int *`. Ty budeme postupně přibližovat
pomocí zvýšení, respektive snížení, o jedna, dokud se nepotkají, což dokážeme ověřit pomocí relačních
operátorů `<`, `>`, `\<=` a `>=`.

====
